### ISSUE TITLE
Flask app doesn't run locally

### ISSUE THREAD

**Issue by rodriguesk** [ClimateMind/climatemind-backend#13]
I tried running the Flask app locally and it fails and gives the following error:

```
$ cd climatemind-backend-master
$ env FLASK_APP=climatemind.py flask run

 * Serving Flask app "climatemind.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
Usage: flask run [OPTIONS]

Error: While importing "climatemind", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/kameronr/Documents/personal/climate change outreach/new uploads/climatemind-backend-master/climatemind.py", line 1, in <module>
    from knowledge_graph import app
  File "/Users/kameronr/Documents/personal/climate change outreach/new uploads/climatemind-backend-master/knowledge_graph/__init__.py", line 5, in <module>
    from knowledge_graph import routes
  File "/Users/kameronr/Documents/personal/climate change outreach/new uploads/climatemind-backend-master/knowledge_graph/routes.py", line 7, in <module>
    from knowledge_graph.Mind import Mind
  File "/Users/kameronr/Documents/personal/climate change outreach/new uploads/climatemind-backend-master/knowledge_graph/Mind.py", line 2, in <module>
    from knowledge_graph import make_network
  File "/Users/kameronr/Documents/personal/climate change outreach/new uploads/climatemind-backend-master/knowledge_graph/make_network.py", line 3, in <module>
    from network_class import Network
ModuleNotFoundError: No module named 'network_class'
```

**Comment by ppython** [comment]
Fixed in https://github.com/ClimateMind/climatemind-backend/commit/678f41e9b42c7eb1b2cbd315b7fef3285d820a8f
